name: CI tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_dbtenv_package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbtenv
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build package
        run: python -m poetry build
  build_dbtenv_dbt_alias_package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbtenv-dbt-alias
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build package
        run: python -m poetry build
