name: Publish dbtenv and dbtenv-dbt-alias releases to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish_dbtenv_package:
    defaults:
      run:
        working-directory: dbtenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build package
        run: python -m poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dbtenv/dist
  publish_dbtenv_dbt_alias_package:
    defaults:
      run:
        working-directory: dbtenv-dbt-alias
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build package
        run: python -m poetry build

      - name: ls
        run: ls

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dbtenv-dbt-alias/dist

